### ISSUE TITLE
CSS file is not included to the component by default

### ISSUE THREAD

**Issue by Ohar** [react-component/tabs#51]
For some reason `/assets/index.css` is not included by component `rc-tabs` its own and that`s why I need to include it separately in any my component where I want to use `rc-tabs`.

Example of thing I need to do
![import Tabs, {TabPane} from 'rc-tabs';
import 'rc-tabs/assets/index.css'; // TODO: Get why it is not imported with 'rc-tabs' component](https://camo.githubusercontent.com/637c75898834aeaaa4b0aa3933c8ec0a690c8b6a/68747470733a2f2f7075752e73682f74566370612f383035626136643839652e706e67)

I am not sure it`s a bug, but it looks like not a nice planned feature.

Why is it so?

**Comment by paranoidjk** [comment]
Because the stylesheet is optional, for example: https://github.com/react-component/tabs/issues/52
We support users use `props.prefixCls` to custom the style, this is very import for something like 
[ant-design](https://github.com/ant-design/ant-design) or  [ant-design-mobile](https://github.com/ant-design/ant-design-mobile) which based on `rc-tabs`, but have their own design style.

**Comment by paranoidjk** [comment]
going to close this, if you have any further question, feel free to reopen this :)
